server: {port: 8104}
spring: {application: {name: library-circulation-service}, datasource: {url: 'jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/library_cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai', username: root, password: '${MYSQL_PASSWORD:Library@2026}'}, cloud: {nacos: {discovery: {server-addr: '${NACOS_ADDR:localhost:8848}'}}}}
mybatis-plus: {configuration: {map-underscore-to-camel-case: true}}
